name: Build FireDog Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Build FireDog
        run: npm run build

      - name: Upload instalador
        uses: actions/upload-artifact@v3
        with:
          name: FireDog-Windows
          path: dist/*


      
